apiVersion: 1

datasources:
  - name: prometheus-prod
    uid: prometheus-prod
    type: prometheus
    access: proxy
    url: http://prometheus-prod.railway.internal:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s

  - name: loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki.railway.internal:3100
    editable: false
    jsonData:
      maxLines: 1000
